---

- name: gather dmi.bios-vendor fact
  raw: /usr/sbin/dmidecode -s bios-vendor
  register: internal_dmi_bios_vendor_cmd
  ignore_errors: yes
  become: yes

- name: set dmi_bios_vendor
  set_fact:
    dmi_bios_vendor: "{{ internal_dmi_bios_vendor_cmd['stdout'] | trim }}"

- name: gather dmi.bios-version fact
  raw: /usr/sbin/dmidecode -s bios-version
  register: internal_dmi_bios_version_cmd
  ignore_errors: yes
  become: yes

- name: set dmi_bios_version
  set_fact:
    dmi_bios_version: "{{ internal_dmi_bios_version_cmd['stdout'] | trim }}"

- name: gather dmi.system-manufacturer fact
  raw: /usr/sbin/dmidecode | grep -A4 'System Information' | grep 'Manufacturer' | sed -n -e 's/^.*Manufacturer:\s//p'
  register: internal_dmi_system_manufacturer_cmd
  ignore_errors: yes
  become: yes

- name: set dmi_system_manufacturer
  set_fact:
    dmi_system_manufacturer: "{{ internal_dmi_system_manufacturer_cmd['stdout'] | trim }}"

- name: gather dmi.processor-family fact
  raw: /usr/sbin/dmidecode -s processor-family
  register: internal_dmi_processor_family_cmd
  ignore_errors: yes
  become: yes

- name: set dmi_processor_family
  set_fact:
    dmi_processor_family: "{{ internal_dmi_processor_family_cmd['stdout'] | trim }}"
