---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "ip address show"

- name: gather 'ip address show' fact (no sudo)
  raw: export LANG=C LC_ALL=C; ip address show
  register: internal_ip_address_show_cmd
  ignore_errors: yes
  when: '(not user_has_sudo) and internal_have_ip_user'

- name: gather 'ip address show' fact (sudo)
  raw: export LANG=C LC_ALL=C; ip address show
  register: internal_sudo_ip_address_show_cmd
  ignore_errors: yes
  become: yes
  when: 'user_has_sudo and internal_have_ip'

- name: extract result value for 'ip address show' (no sudo)
  set_fact:
    # NOTE: We want to process the related output in two different ways, but the current
    # quipucords Processor class behavior requires us to include it in two facts.
    ip_address_show_ipv4: "{{ internal_ip_address_show_cmd | default(None) }}"
    ip_address_show_mac: "{{ internal_ip_address_show_cmd | default(None) }}"
  ignore_errors: yes
  when: '(not user_has_sudo) and "stdout_lines" in internal_ip_address_show_cmd'

- name: extract result value for 'ip address show' (sudo)
  set_fact:
    # NOTE: We want to process the related output in two different ways, but the current
    # quipucords Processor class behavior requires us to include it in two facts.
    ip_address_show_ipv4: "{{ internal_sudo_ip_address_show_cmd | default(None) }}"
    ip_address_show_mac: "{{ internal_sudo_ip_address_show_cmd | default(None) }}"
  ignore_errors: yes
  when: 'user_has_sudo and "stdout_lines" in internal_sudo_ip_address_show_cmd'
