---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "ip address show"

- name: gather 'ip address show' fact
  raw: /sbin/ip address show
  register: internal_ip_address_show_cmd
  ignore_errors: yes
  become: '{{user_has_sudo}}'
  when: 'internal_have_ip'

- name: extract result value for 'ip address show'
  set_fact:
    # NOTE: We want to process the related output in two different ways, but the current
    # quipucords Processor class behavior requires us to include it in two facts.
    ip_address_show_ipv4: "{{ internal_ip_address_show_cmd | default(None) }}"
    ip_address_show_mac: "{{ internal_ip_address_show_cmd | default(None) }}"
  ignore_errors: yes
  when: '"stdout_lines" in internal_ip_address_show_cmd'
