---
# Custom task based on upstream tekton and konflux docs.
# Given this is pipeline requires using trusted artifacts, some boilerplate is required
# https://konflux-ci.dev/docs/advanced-how-tos/using-trusted-artifacts/#migrate-to-trusted-artifacts
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-version-labels
spec:
  description: |
    Custom task that generates dynamic labels based on "pyproject.toml" version. This produce the labels
    "version" and "version_minor".
  params:
    - description: The Trusted Artifact URI pointing to the artifact with the application source code.
      name: SOURCE_ARTIFACT
      type: string
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  volumes:
    # New volume to store a copy of the source code accessible only to this Task.
    - name: workdir
      emptyDir: {}
  results:
    - name: labels
      description: The rendered labels
      type: array
  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
    - name: generate-version-labels
      image: quay.io/konflux-ci/yq@sha256:d4feadf33854f9d9aef4e7deed45ba61d4c69d3fc2a685e82ad8ba12fc8bbae1
      workingDir: /var/workdir/source
      script: |
        echo "Extracting full version (X.Y.Z) from pyproject.toml"
        VERSION=$(yq -r '.project.version' pyproject.toml)
        echo "version=${VERSION}"

        # fail if VERSION doesn't conform to the expected format
        if [[ -z "${VERSION}" || ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "version=${VERSION} does not match the required pattern."
          exit 1
        fi

        echo "Computing minor version (X.Y only)"
        VERSION_MINOR=$(yq -r '.project.version | split(".").[:2] | join(".")' pyproject.toml)
        echo "version_minor=${VERSION_MINOR}"

        # fail if VERSION_MINOR doesn't conform to the expected format
        if [[ -z "${VERSION_MINOR}" || ! "${VERSION_MINOR}" =~ ^[0-9]+\.[0-9]+$ ]]; then
          echo "version_minor=${VERSION_MINOR} does not match the required pattern."
          exit 1
        fi

        echo "Writing results..."
        # version and version_minor are the labels expected in downstream RPA configuration
        echo [\"version=${VERSION}\", \"version_minor=${VERSION_MINOR}\"] | tee "$(results.labels.path)"
