---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "system_purpose"

- name: gather system purpose json
  raw: if [ -f /etc/rhsm/syspurpose/syspurpose.json ] ; then cat /etc/rhsm/syspurpose/syspurpose.json 2>/dev/null; fi
  register: system_purpose_json
  ignore_errors: yes
