pep8:
  full: true
doc-warnings: true
test-warnings: false
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
  - dev-requirements.txt
ignore-paths:
  - docs
  - deploy
  - client
  - rel-eng
  - roles
ignore-patterns:
  - ^tests*\.py$
  - (^|/)docs(/|$)
python-targets:
  - 3
