codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 70..90

  status:
    patch:
      default:
        target: 80%
        threshold: 5
    project:
      default: false
      quipucords:
        target: auto
        threshold: 5
        paths:
          - "quipucords/"
