---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "check_dependencies"

- name: gather internal_have_dmidecode_cmd
  raw: command -v /usr/sbin/dmidecode
  register: internal_have_dmidecode_cmd
  ignore_errors: yes

- name: set internal_have_dmidecode
  set_fact:
    internal_have_dmidecode: "{{ internal_have_dmidecode_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_tune2fs_cmd
  raw: command -v tune2fs
  register: internal_have_tune2fs_cmd
  ignore_errors: yes

- name: set internal_have_tune2fs
  set_fact:
    internal_have_tune2fs: "{{ internal_have_tune2fs_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_yum_cmd
  raw: command -v yum
  register: internal_have_yum_cmd
  ignore_errors: yes

- name: set internal_have_yum
  set_fact:
    internal_have_yum: "{{ internal_have_yum_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_java_cmd
  raw: command -v java
  register: internal_have_java_cmd
  ignore_errors: yes

- name: set internal_have_java
  set_fact:
    internal_have_java: "{{ internal_have_java_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_rpm_cmd
  raw: command -v rpm
  register: internal_have_rpm_cmd
  ignore_errors: yes

- name: set internal_have_rpm
  set_fact:
    internal_have_rpm: "{{ internal_have_rpm_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_subscription_manager_cmd
  raw: command -v subscription-manager
  register: internal_have_subscription_manager_cmd
  ignore_errors: yes

- name: set internal_have_subscription_manager
  set_fact:
    internal_have_subscription_manager: "{{ internal_have_subscription_manager_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_virsh_cmd
  raw: command -v virsh
  register: internal_have_virsh_cmd
  ignore_errors: yes

- name: set internal_have_virsh
  set_fact:
    internal_have_virsh: "{{ internal_have_virsh_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_virt_what_cmd
  raw: command -v virt-what
  register: internal_have_virt_what_cmd
  ignore_errors: yes

- name: set internal_have_virt_what
  set_fact:
    internal_have_virt_what: "{{ internal_have_virt_what_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_locate_cmd
  raw: command -v locate
  register: internal_have_locate_cmd
  ignore_errors: yes

- name: set internal_have_locate
  set_fact:
    internal_have_locate: "{{ internal_have_locate_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_have_systemctl_cmd
  raw: command -v systemctl
  register: internal_have_systemctl_cmd
  ignore_errors: yes

- name: set internal_have_systemctl
  set_fact:
    internal_have_systemctl: "{{ internal_have_systemctl_cmd.get('rc') == 0 }}"
  ignore_errors: yes

- name: gather internal_whereis_chkconfig_cmd
  raw: whereis chkconfig
  register: internal_whereis_chkconfig_cmd
  ignore_errors: yes

- name: set internal_have_chkconfig
  set_fact:
    internal_have_chkconfig: true
  ignore_errors: yes
  when: (internal_whereis_chkconfig_cmd.get('rc') == 0 and internal_whereis_chkconfig_cmd.get('stdout_lines') != ['chkconfig:'])

- name: gather internal_whereis_ifconfig_cmd
  raw: whereis ifconfig
  register:  internal_whereis_ifconfig_cmd
  ignore_errors: yes

- name: set internal_have_ifconfig
  set_fact:
    internal_have_ifconfig: "{{ internal_whereis_ifconfig_cmd.get('rc') == 0  }} and {{ internal_whereis_ifconfig_cmd.get('stdout_lines') != ['ifconfig:']}}"
  ignore_errors: yes

- name: gather internal_have_unzip_cmd
  raw: command -v unzip
  register: internal_have_unzip_cmd
  ignore_errors: yes

- name: set internal_have_unzip
  set_fact:
    internal_have_unzip: "{{ internal_have_unzip_cmd.get('rc') == 0 }}"
  ignore_errors: yes
