const API_SOURCE_NAME = 'name';
const API_SOURCE_TYPE = 'source_type';
const API_SOURCE_HOSTS = 'hosts';
const API_SOURCE_PORT = 'port';
const API_SOURCE_CREDENTIALS = 'credentials';
const API_SOURCE_SAT_VERSION = 'satellite_version';
const API_SOURCE_SSL_CERT = 'ssl_cert_verify';
const API_SOURCE_SSL_PROTOCOL = 'ssl_protocol';
const API_SOURCE_SSL_DISABLE = 'disable_ssl';

const API_RESPONSE_CREDENTIALS_COUNT = 'count';
const API_RESPONSE_CREDENTIALS_RESULTS = 'results';

const API_RESPONSE_SOURCES_COUNT = 'count';
const API_RESPONSE_SOURCES_RESULTS = 'results';

const API_RESPONSE_SCANS_COUNT = 'count';
const API_RESPONSE_SCANS_RESULTS = 'results';

const API_RESPONSE_JOBS_RESULTS = 'results';

const apiTypes = {
  API_SOURCE_CREDENTIALS,
  API_SOURCE_HOSTS,
  API_SOURCE_NAME,
  API_SOURCE_PORT,
  API_SOURCE_SAT_VERSION,
  API_SOURCE_SSL_CERT,
  API_SOURCE_SSL_DISABLE,
  API_SOURCE_SSL_PROTOCOL,
  API_SOURCE_TYPE,
  API_RESPONSE_CREDENTIALS_COUNT,
  API_RESPONSE_CREDENTIALS_RESULTS,
  API_RESPONSE_SOURCES_COUNT,
  API_RESPONSE_SOURCES_RESULTS,
  API_RESPONSE_SCANS_COUNT,
  API_RESPONSE_SCANS_RESULTS,
  API_RESPONSE_JOBS_RESULTS
};

export {
  apiTypes as default,
  apiTypes,
  API_SOURCE_CREDENTIALS,
  API_SOURCE_HOSTS,
  API_SOURCE_NAME,
  API_SOURCE_PORT,
  API_SOURCE_SAT_VERSION,
  API_SOURCE_SSL_CERT,
  API_SOURCE_SSL_DISABLE,
  API_SOURCE_SSL_PROTOCOL,
  API_SOURCE_TYPE,
  API_RESPONSE_CREDENTIALS_COUNT,
  API_RESPONSE_CREDENTIALS_RESULTS,
  API_RESPONSE_SOURCES_COUNT,
  API_RESPONSE_SOURCES_RESULTS,
  API_RESPONSE_SCANS_COUNT,
  API_RESPONSE_SCANS_RESULTS,
  API_RESPONSE_JOBS_RESULTS
};
