# Generated by Django 2.1.5 on 2019-01-23 18:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial_postgres"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymentsreport",
            name="report_platform_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="detailsreport",
            name="report_platform_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="systemfingerprint",
            name="etc_machine_id",
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AddField(
            model_name="systemfingerprint",
            name="vm_host_core_count",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="version",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="infrastructure_type",
            field=models.CharField(
                choices=[
                    ("bare_metal", "Bare Metal"),
                    ("virtualized", "Virtualized"),
                    ("hypervisor", "Hypervisor"),
                    ("unknown", "Unknown"),
                ],
                max_length=12,
            ),
        ),
    ]
