# Generated by Django 2.1.3 on 2018-11-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_postgres'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfingerprint',
            name='system_intent_addons',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='systemfingerprint',
            name='system_intent_role',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='systemfingerprint',
            name='system_intent_sla',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='systemfingerprint',
            name='system_intent_usage_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
