# Generated by Django 4.2.23 on 2025-07-17 22:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="global_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
