# Generated by Django 2.1.3 on 2018-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_postgres'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfingerprint',
            name='etc_machine_id',
            field=models.TextField(null=True),
        ),
    ]
