# Generated by Django 2.0 on 2018-10-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_postgres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentsreport',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('completed', 'completed')], default='pending', max_length=16),
        ),
    ]
