# Generated by Django 5.2.8 on 2026-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="origin",
            field=models.CharField(
                choices=[
                    ("local", "local"),
                    ("uploaded", "uploaded"),
                    ("merged", "merged"),
                ],
                default="local",
            ),
        ),
    ]
