# Generated by Django 5.2.8 on 2025-11-24 19:32

from django.db import migrations

import api.encrypted_charfield


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="auth_token",
            field=api.encrypted_charfield.EncryptedCharField(
                blank=True, max_length=6000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="become_password",
            field=api.encrypted_charfield.EncryptedCharField(
                blank=True, max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="password",
            field=api.encrypted_charfield.EncryptedCharField(
                blank=True, max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="ssh_key",
            field=api.encrypted_charfield.EncryptedCharField(
                blank=True, max_length=65536, null=True
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="ssh_passphrase",
            field=api.encrypted_charfield.EncryptedCharField(
                blank=True, max_length=1024, null=True
            ),
        ),
    ]
