# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='exclude_hosts',
            field=models.TextField(null=True),
        ),
    ]
