# Generated by Django 2.1.3 on 2018-11-30 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemfingerprint_etc_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsreport',
            name='report_platform_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='detailsreport',
            name='report_platform_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
