# Generated by Django 5.2.11 on 2026-02-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.encrypted_charfield


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_report_origin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "token_type",
                    models.CharField(
                        choices=[("insights-jwt", "insights-jwt")], max_length=32
                    ),
                ),
                (
                    "token",
                    api.encrypted_charfield.EncryptedCharField(
                        blank=True, max_length=32768, null=True
                    ),
                ),
                (
                    "metadata",
                    api.encrypted_charfield.EncryptedCharField(
                        blank=True, max_length=4096, null=True
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Secure Token",
                "verbose_name_plural": "Secure Tokens",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True)),
                        fields=("name",),
                        name="unique_secure_token_name",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "name"), name="unique_user_secure_token_name"
                    ),
                ],
            },
        ),
    ]
