# Generated by Django 2.1.5 on 2019-02-05 23:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_insights_reports"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deploymentsreport",
            old_name="cached_json",
            new_name="cached_fingerprints",
        ),
        migrations.AddField(
            model_name="deploymentsreport",
            name="cached_insights",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="systemfingerprint",
            name="system_platform_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="systemfingerprint",
            name="cpu_core_per_socket",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="scanoptions",
            name="max_concurrency",
            field=models.PositiveIntegerField(default=25),
        ),
    ]
