# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_source_exclude_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceoptions',
            name='use_paramiko',
            field=models.NullBooleanField(default=False),
        ),
    ]
