# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-31 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jws_and_paramiko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfingerprint',
            name='infrastructure_type',
            field=models.CharField(choices=[('bare_metal', 'Bare Metal'), ('virtualized', 'Virtualized'), ('unknown', 'Unknown')], default='unknown', max_length=12),
        ),
    ]
