# Generated by Django 2.1.7 on 2019-03-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_system_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfingerprint',
            name='cpu_core_per_socket',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
