# Generated by Django 5.2.12 on 2026-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_securetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securetoken",
            name="token_type",
            field=models.CharField(
                choices=[("lightspeed-jwt", "lightspeed-jwt")], max_length=32
            ),
        ),
    ]
