# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sourceoptions_use_paramiko'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabledoptionalproductsoptions',
            name='jboss_ws',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendedproductsearchoptions',
            name='jboss_ws',
            field=models.BooleanField(default=False),
        ),
    ]
