# Generated by Django 2.1.3 on 2018-12-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_platform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.TextField(null=True),
        ),
    ]
