# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_postgres_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('network', 'network'), ('vcenter', 'vcenter'), ('satellite', 'satellite')], max_length=12),
        ),
    ]
