# Generated by Django 2.1.5 on 2019-01-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_version_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfingerprint',
            name='vm_host_core_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
