# Generated by Django 2.1.7 on 2019-03-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemfingerprint_cpu_core_per_socket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanoptions',
            name='max_concurrency',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
