# Generated by Django 5.2.12 on 2026-03-27 11:00

from django.db import migrations, models

import api.encrypted_fields


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_publish_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securetoken",
            name="metadata",
            field=api.encrypted_fields.EncryptedDictField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="securetoken",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("lightspeed-jwt", "lightspeed-jwt"),
                    ("hashicorp-vault", "hashicorp-vault"),
                ],
                max_length=32,
            ),
        ),
    ]
