# Generated by Django 2.2.4 on 2019-08-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_systemfingerprint_system_platform_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemfingerprint",
            name="virtual_host_uuid",
            field=models.CharField(max_length=36, null=True),
        ),
    ]
