# Generated by Django 2.1.5 on 2019-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_systemfingerprint_vm_host_core_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemfingerprint',
            name='infrastructure_type',
            field=models.CharField(choices=[('bare_metal', 'Bare Metal'), ('virtualized', 'Virtualized'), ('hypervisor', 'Hypervisor'), ('unknown', 'Unknown')], max_length=12),
        ),
    ]
