# Generated by Django 5.2.12 on 2026-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_publish_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishrequest",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("expired_token", "Expired Token"),
                    ("network_unreachable", "Network Unreachable"),
                    ("invalid_report", "Invalid Report"),
                    ("server_error", "Server Error"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
