# Generated by Django 2.2.6 on 2019-11-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_systemfingerprint_virtual_host_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfingerprint',
            name='system_purpose',
            field=models.TextField(null=True),
        ),
    ]
