# Generated by Django 2.2.6 on 2019-11-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_systemfingerprint_system_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfingerprint',
            name='cloud_provider',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
