# Generated by Django 5.2.13 on 2026-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_securetoken_metadata_token_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="vault_mount_point",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="vault_secret_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
