# Generated by Django 3.1.14 on 2022-05-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_release_0_9_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemfingerprint",
            name="architecture",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="bios_uuid",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="cloud_provider",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="cpu_core_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="cpu_core_per_socket",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="cpu_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="cpu_socket_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="etc_machine_id",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="insights_client_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="ip_addresses",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="mac_addresses",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="os_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="os_release",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="os_version",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="redhat_certs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="redhat_package_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="subscription_manager_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="system_addons",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="system_creation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="system_last_checkin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="system_purpose",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="system_role",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="system_service_level_agreement",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="system_usage_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="system_user_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="user_login_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="virtual_host_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="virtual_host_uuid",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="virtualized_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="vm_cluster",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="vm_datacenter",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="vm_dns_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="vm_host_core_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="vm_host_socket_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="vm_state",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="vm_uuid",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
