# Generated by Django 3.1.14 on 2022-07-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_null_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scantask",
            unique_together={("job", "scan_type", "source")},
        ),
    ]
