# Generated by Django 5.2.14 on 2026-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_add_vault_fields_to_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="vault_secret_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
