# Generated by Django 2.2.6 on 2019-12-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_systemfingerprint_cloud_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfingerprint',
            name='system_user_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemfingerprint',
            name='user_login_history',
            field=models.TextField(null=True),
        ),
    ]
