# Generated by Django 2.2.6 on 2019-12-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfingerprint',
            name='cpu_hyperthreading',
            field=models.NullBooleanField(),
        ),
    ]
