# Generated by Django 3.2.14 on 2022-08-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_constrain_scantask"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemfingerprint",
            name="system_memory_bytes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
