# Generated by Django 2.2.8 on 2019-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_systemfingerprint_cpu_hyperthreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsreport',
            name='cached_masked_csv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='deploymentsreport',
            name='cached_masked_fingerprints',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detailsreport',
            name='cached_masked_csv',
            field=models.TextField(null=True),
        ),
    ]
