# Generated by Django 3.2.14 on 2022-09-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_update_system_memory_bytes"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="auth_token",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="cred_type",
            field=models.CharField(
                choices=[
                    ("network", "network"),
                    ("vcenter", "vcenter"),
                    ("satellite", "satellite"),
                    ("openshift", "openshift"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="username",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
