# Generated by Django 5.2.17 on 2026-10-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_rename_uname_processor_raw_fact"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemfingerprint",
            name="rhel_version",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
