# Generated by Django 3.2.14 on 2022-09-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_add_openshift_credential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("network", "network"),
                    ("vcenter", "vcenter"),
                    ("satellite", "satellite"),
                    ("openshift", "openshift"),
                ],
                max_length=12,
            ),
        ),
    ]
