# Generated by Django 5.2.17 on 2026-10-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_systemfingerprint_rhel_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatereport",
            name="rhel_by_version",
            field=models.JSONField(default=dict),
        ),
    ]
