# Generated by Django 3.2.14 on 2022-10-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_add_openshift_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemfingerprint",
            name="container_images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemfingerprint",
            name="container_labels",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
