# Generated by Django 3.2.16 on 2022-12-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_openshift_fingerprints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemfingerprint",
            name="container_images",
        ),
        migrations.RemoveField(
            model_name="systemfingerprint",
            name="container_labels",
        ),
    ]
