# Generated by Django 3.2.17 on 2023-02-13 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_unused_fingerprints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deploymentsreport",
            name="cached_insights",
        ),
    ]
