# Generated by Django 3.2.17 on 2023-03-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_drop_cached_insights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymentsreport",
            name="cached_fingerprints",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="deploymentsreport",
            name="cached_masked_fingerprints",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="sourceoptions",
            name="disable_ssl",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="sourceoptions",
            name="ssl_cert_verify",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="sourceoptions",
            name="use_paramiko",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="cpu_hyperthreading",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="systemfingerprint",
            name="is_redhat",
            field=models.BooleanField(null=True),
        ),
    ]
