# Generated by Django 3.2.17 on 2023-03-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_migrate_user_login_history_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemfingerprint",
            name="ip_addresses",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
