# Generated by Django 3.2.17 on 2023-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_migrate_ip_addresses_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemfingerprint",
            name="mac_addresses",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
