# Generated by Django 3.2.17 on 2023-03-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_migrate_mac_addresses_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="exclude_hosts",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="hosts",
            field=models.JSONField(default=list),
        ),
    ]
