# Generated by Django 3.2.17 on 2023-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_migrate_metadata_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemfingerprint",
            name="sources",
            field=models.JSONField(null=True),
        ),
    ]
