# Generated by Django 3.2.17 on 2023-03-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_migrate_systemfingerprint_sources_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailsreport",
            name="sources",
            field=models.JSONField(null=True),
        ),
    ]
