# Generated by Django 3.2.17 on 2023-03-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_migrate_details_report_sources_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="version",
            field=models.JSONField(null=True),
        ),
    ]
