# Generated by Django 3.2.17 on 2023-03-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_migrate_product_version_metadata_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitlement",
            name="metadata",
            field=models.JSONField(null=True),
        ),
    ]
