# Generated by Django 3.2.17 on 2023-03-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_migrate_entitlement_metadata_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedproductsearchoptions",
            name="search_directories",
            field=models.JSONField(null=True),
        ),
    ]
