# Generated by Django 4.1.7 on 2023-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_migrate_rawfact_value_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="cred_type",
            field=models.CharField(
                choices=[
                    ("network", "network"),
                    ("vcenter", "vcenter"),
                    ("satellite", "satellite"),
                    ("openshift", "openshift"),
                    ("ansible", "ansible"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("network", "network"),
                    ("vcenter", "vcenter"),
                    ("satellite", "satellite"),
                    ("openshift", "openshift"),
                    ("ansible", "ansible"),
                ],
                max_length=12,
            ),
        ),
    ]
