# Generated by Django 4.2.3 on 2023-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_add_ssh_keyvalue_to_credential"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="auth_token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="become_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sudo", "sudo"),
                    ("su", "su"),
                    ("pbrun", "pbrun"),
                    ("pfexec", "pfexec"),
                    ("doas", "doas"),
                    ("dzdo", "dzdo"),
                    ("ksu", "ksu"),
                    ("runas", "runas"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="become_password",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="become_user",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="password",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="ssh_key",
            field=models.CharField(blank=True, max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="ssh_keyfile",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="ssh_passphrase",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="username",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
