# Generated by Django 4.2.4 on 2023-09-13 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_alter_credential_auth_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deploymentsreport",
            name="cached_masked_csv",
        ),
        migrations.RemoveField(
            model_name="deploymentsreport",
            name="cached_masked_fingerprints",
        ),
        migrations.RemoveField(
            model_name="detailsreport",
            name="cached_masked_csv",
        ),
    ]
