# Generated by Django 4.2.4 on 2023-09-13 21:54

from django.db import migrations, models

import api.inspectresult.model


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0034_remove_deploymentsreport_cached_masked_csv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailsreport",
            name="sources",
            field=models.JSONField(
                default=list, encoder=api.inspectresult.model.RawFactEncoder
            ),
        ),
    ]
