# Generated by Django 4.2.4 on 2023-09-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_detailsreport_sources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deploymentsreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="detailsreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="scanjob",
            name="report_id",
        ),
    ]
