# Generated by Django 4.2.4 on 2023-09-21 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_remove_deploymentsreport_report_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DetailsReport",
            new_name="Report",
        ),
        migrations.RemoveField(
            model_name="report",
            name="report_type",
        ),
    ]
