# Generated by Django 4.2.4 on 2023-09-22 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_rename_details_report_scanjob_report_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scantask",
            name="details_report",
        ),
    ]
