# Generated by Django 4.2.1 on 2023-10-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_remove_scantask_details_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="cred_type",
            field=models.CharField(
                choices=[
                    ("network", "network"),
                    ("vcenter", "vcenter"),
                    ("satellite", "satellite"),
                    ("openshift", "openshift"),
                    ("ansible", "ansible"),
                    ("acs", "acs"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("network", "network"),
                    ("vcenter", "vcenter"),
                    ("satellite", "satellite"),
                    ("openshift", "openshift"),
                    ("ansible", "ansible"),
                    ("acs", "acs"),
                ],
                max_length=12,
            ),
        ),
    ]
