# Generated by Django 4.2.4 on 2023-10-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_remove_scantask_details_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("fqdn", models.CharField(blank=True, max_length=100, null=True)),
                ("mac_addresses", models.JSONField(blank=True, null=True)),
                ("ip_addresses", models.JSONField(blank=True, null=True)),
                ("bios_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "insights_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("satellite_id", models.UUIDField(blank=True, null=True)),
                ("subscription_manager_id", models.UUIDField(blank=True, null=True)),
                (
                    "provider_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provider_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("number_of_cpus", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "number_of_sockets",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cores_per_socket",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "system_memory_bytes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "infrastructure_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "infrastructure_vendor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("os_release", models.CharField(blank=True, max_length=100, null=True)),
                ("arch", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cloud_provider",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("system_purpose", models.JSONField(default=dict)),
                ("network_interfaces", models.JSONField(default=list)),
                (
                    "etc_machine_id",
                    models.CharField(blank=True, max_length=48, null=True),
                ),
                ("cpu_hyperthreading", models.BooleanField(null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="api.report",
                    ),
                ),
            ],
        ),
    ]
