# Generated by Django 4.2.5 on 2023-10-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_systemfingerprint_installed_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="auth_token",
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
