# Generated by Django 4.2.5 on 2023-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_alter_credential_auth_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="cred_type",
            field=models.CharField(
                choices=[
                    ("network", "network"),
                    ("vcenter", "vcenter"),
                    ("satellite", "satellite"),
                    ("openshift", "openshift"),
                    ("ansible", "ansible"),
                    ("rhacs", "rhacs"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("network", "network"),
                    ("vcenter", "vcenter"),
                    ("satellite", "satellite"),
                    ("openshift", "openshift"),
                    ("ansible", "ansible"),
                    ("rhacs", "rhacs"),
                ],
                max_length=12,
            ),
        ),
    ]
