# Generated by Django 4.2.7 on 2023-12-07 12:37

import django.utils.timezone
from django.db import migrations, models


def update_timestamps(apps, schema_editor):
    """Populate new fields of the existing rows."""
    Credential = apps.get_model("api", "Credential")

    Credential.objects.all().update(
        created_at=django.utils.timezone.now(),
        updated_at=django.utils.timezone.now(),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_alter_credential_cred_type_alter_source_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.RunPython(update_timestamps, reverse_code=migrations.RunPython.noop),
    ]
