# Generated by Django 4.2.9 on 2024-01-31 23:10

from django.db import migrations, models


def merge_source_options(apps, _schema_editor):
    """For each SourceOption, copy the option to the Source model."""
    source_model = apps.get_model("api", "Source")

    for source in source_model.objects.all():
        if source.options:
            source.disable_ssl = source.options.disable_ssl
            source.ssl_cert_verify = source.options.ssl_cert_verify
            source.ssl_protocol = source.options.ssl_protocol
            source.use_paramiko = source.options.use_paramiko
            source.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_credential_created_at_credential_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="disable_ssl",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="ssl_cert_verify",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="ssl_protocol",
            field=models.CharField(
                choices=[
                    ("SSLv23", "SSLv23"),
                    ("TLSv1", "TLSv1"),
                    ("TLSv1_1", "TLSv1_1"),
                    ("TLSv1_2", "TLSv1_2"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="use_paramiko",
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(
            merge_source_options, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="source",
            name="options",
        ),
        migrations.DeleteModel(
            name="SourceOptions",
        ),
    ]
