# Generated by Django 4.2.10 on 2024-02-13 11:44

from django.db import migrations, models

SUPPORTED_PRODUCTS = ["jboss_eap", "jboss_fuse", "jboss_ws", "jboss_brms"]
SEARCH_DIRECTORIES = "search_directories"


def merge_enabled_optional_products(scan, disabled_optional_products):
    """Merge DisabledOptionalProducts."""
    if not disabled_optional_products:
        return

    enabled_optional_products = {}
    for prod in SUPPORTED_PRODUCTS:
        flag = getattr(disabled_optional_products, prod, None)
        if flag is not None:
            enabled_optional_products[prod] = not flag
    scan.enabled_optional_products = enabled_optional_products


def merge_enabled_extended_product_search(scan, enabled_extended_product_search):
    """Merge EnabledExtendedProductSearch."""
    if not enabled_extended_product_search:
        return

    options = {}
    for prod in SUPPORTED_PRODUCTS:
        flag = getattr(enabled_extended_product_search, prod, None)
        if flag is not None:
            options[prod] = flag
    search_directories = getattr(
        enabled_extended_product_search,
        SEARCH_DIRECTORIES,
        None,
    )
    if search_directories is not None:
        options[SEARCH_DIRECTORIES] = search_directories
    if options:
        scan.enabled_extended_product_search = options


def merge_scan_options(apps, _schema_editor):
    """For each ScanOption, copy the option to the Scan model."""
    scan_model = apps.get_model("api", "Scan")

    for scan in scan_model.objects.all():
        scan_options = scan.options
        if scan_options:
            scan.max_concurrency = scan_options.max_concurrency
            merge_enabled_optional_products(
                scan, scan_options.disabled_optional_products
            )
            merge_enabled_extended_product_search(
                scan, scan_options.enabled_extended_product_search
            )
            scan.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_merge_source_options_with_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="max_concurrency",
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="scan",
            name="enabled_optional_products",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="enabled_extended_product_search",
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(
            merge_scan_options, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="scan",
            name="options",
        ),
        migrations.RemoveField(
            model_name="scanjob",
            name="options",
        ),
        migrations.DeleteModel(
            name="ScanOptions",
        ),
        migrations.DeleteModel(
            name="DisabledOptionalProductsOptions",
        ),
        migrations.DeleteModel(
            name="ExtendedProductSearchOptions",
        ),
    ]
