# Generated by Django 4.2.10 on 2024-03-01 19:45

import logging
from itertools import groupby
from uuid import uuid4

import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger(__name__)


def set_constraints_now(apps, schema_editor):
    """Set constraints now for postgresql."""
    if schema_editor.connection.vendor != "postgresql":
        # we only need this for postgresql because, according to django docs:
        # "On most database backends (all but PostgreSQL), Django will split the SQL
        # into individual statements prior to executing them."
        # https://docs.djangoproject.com/en/4.2/ref/migration-operations/#runsql
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def defer_constraints(apps, schema_editor):
    """Rename details_report_sequence to report_sequence."""
    if schema_editor.connection.vendor != "postgresql":
        # we only need this for postgresql because, according to django docs:
        # "On most database backends (all but PostgreSQL), Django will split the SQL
        # into individual statements prior to executing them."
        # https://docs.djangoproject.com/en/4.2/ref/migration-operations/#runsql
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET CONSTRAINTS ALL DEFERRED")


def create_result_set_for_results_with_source(apps, schema_editor):
    """Create ResultSet for results that have a source."""
    InspectResult = apps.get_model("api", "InspectResult")
    ResultSet = apps.get_model("api", "ResultSet")
    ServerInformation = apps.get_model("api", "ServerInformation")
    Report = apps.get_model("api", "Report")

    server_info = ServerInformation.objects.first()
    server_id = server_info.global_identifier if server_info else "unknown"

    qs = InspectResult.objects.exclude(source_id=None).order_by("source_id")
    for _, grouped in groupby(qs, key=lambda r: r.source_id):
        results = list(grouped)
        source = results[0].source
        scan_task = results[0].tasks.filter(scan_type="inspect").first()
        if scan_task is None:
            logger.error(
                "Found InspectResults (ids=%s) not tied to any ScanTask, which is "
                "invalid. These will be deleted.",
                [r.id for r in results],
            )
            # cleanup_invalid_results will take care of the deletion
            continue
        report = Report.objects.filter(
            scanjob__tasks__inspect_results__id=results[0].id
        ).first()
        server_version = report.report_version if report else "unknown"
        result_set = ResultSet.objects.create(
            source_type=source.source_type,
            source_name=source.name,
            server_id=server_id,
            server_version=server_version,
            source=source,
        )
        result_set.tasks.add(scan_task)
        result_set.inspect_results.add(*results)


def create_results_for_fingerprint_type_reports(apps, schema_editor):
    """
    Migrate sources data from merged/uploaded reports.

    Fingerprint-type ScanJobs are a special case: they lack RawFacts and
    Sources. This function will create ResultSets, InspectResult and RawFacts
    for these ScanJobs based on the contents of Report.sources.
    """
    InspectResult = apps.get_model("api", "InspectResult")
    ResultSet = apps.get_model("api", "ResultSet")
    Report = apps.get_model("api", "Report")
    RawFact = apps.get_model("api", "RawFact")
    ScanTask = apps.get_model("api", "ScanTask")

    reports = Report.objects.filter(scanjob__scan_type="fingerprint").all()
    for report in reports:
        scan_task = ScanTask.objects.create(
            scan_type="inspect", job=report.scanjob, status="complete"
        )
        if not isinstance(report.sources, list):
            logger.error(
                (
                    "Invalid data structure for sources for report_id=%s. "
                    "This entry will be removed during the migration process. "
                    "See source contents below:\n%s"
                ),
                report.id,
                report.sources,
            )
            continue

        for source in report.sources:
            try:
                # source type is a MUST. if we don't have it, the data is trash.
                # we COULD infer source_type based on the contents of raw facts,
                # but that's not worth the effort.
                source_type = source["source_type"]
            except KeyError:
                logger.error(
                    (
                        "Found a source without source_type for report_id=%s. "
                        "This entry will be ignored during the migration process. "
                        "See source contents below:\n%s"
                    ),
                    report.id,
                    source,
                )
                continue
            list_of_facts = source.get("facts")
            if not isinstance(list_of_facts, list) or not all(
                isinstance(f, dict) for f in list_of_facts
            ):
                logger.error(
                    (
                        "Invalid or absent facts for source in report_id=%s. "
                        "This entry will be ignored during the migration process. "
                        "See source contents below:\n%s"
                    ),
                    report.id,
                    source,
                )
                continue

            result_set = ResultSet.objects.create(
                source_type=source_type,
                source_name=source.get("source_name", "unknown"),
                server_id=source.get("server_id", "unknown"),
                server_version=source.get("report_version", "unknown"),
            )
            result_set.tasks.add(scan_task)
            for facts in list_of_facts:
                inspect_result = InspectResult.objects.create(
                    result_set=result_set, name=str(uuid4()), status="success"
                )
                raw_fact_list = [
                    RawFact(name=k, value=v, inspect_result=inspect_result)
                    for k, v in facts.items()
                ]
                RawFact.objects.bulk_create(raw_fact_list)


def cleanup_invalid_results(apps, schema_editor):
    """Delete all InspectResults that weren't bound to a ResultSet."""
    # There's a very unlikely edge case that wasn't migrated:
    # sourceless results from normal scans. Let's just delete
    # those before making result_set an obligatory field.
    InspectResult = apps.get_model("api", "InspectResult")
    InspectResult.objects.filter(result_set=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_remove_taskinspectionresult_job_inspection_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("network", "network"),
                            ("vcenter", "vcenter"),
                            ("satellite", "satellite"),
                            ("openshift", "openshift"),
                            ("ansible", "ansible"),
                            ("rhacs", "rhacs"),
                        ],
                        max_length=12,
                    ),
                ),
                ("source_name", models.CharField(max_length=64)),
                ("server_id", models.CharField(max_length=36)),
                ("server_version", models.CharField(max_length=64)),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.source",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="result_sets", to="api.scantask"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inspectresult",
            name="result_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.ResultSet",
                related_name="inspect_results",
            ),
        ),
        migrations.RunPython(
            create_result_set_for_results_with_source,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_results_for_fingerprint_type_reports,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            cleanup_invalid_results,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="report",
            name="sources",
        ),
        migrations.RemoveField(
            model_name="inspectresult",
            name="source",
        ),
        migrations.RemoveField(
            model_name="inspectresult",
            name="tasks",
        ),
        migrations.RunPython(set_constraints_now, reverse_code=defer_constraints),
        migrations.AlterField(
            model_name="inspectresult",
            name="result_set",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.ResultSet",
                related_name="inspect_results",
            ),
        ),
        migrations.RunPython(defer_constraints, reverse_code=set_constraints_now),
    ]
