# Generated by Django 4.2.11 on 2024-04-29 15:04

from django.db import migrations, models

import api.common.common_report


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_alter_deploymentsreport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_version",
            field=models.CharField(
                default=api.common.common_report.create_report_version, max_length=64
            ),
        ),
    ]
