# Generated by Django 4.2.19 on 2025-03-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_remove_systemfingerprint_user_login_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='http_proxy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='https_proxy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
