# Generated by Django 4.2.20 on 2025-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_alter_scan_scan_type_alter_scanjob_scan_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="proxy_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
