const ADD_CREDENTIAL = 'ADD_CREDENTIAL';
const DELETE_CREDENTIAL = 'DELETE_CREDENTIAL';
const DELETE_CREDENTIALS = 'DELETE_CREDENTIALS';
const GET_CREDENTIAL = 'GET_CREDENTIAL';
const GET_CREDENTIALS = 'GET_CREDENTIALS';
const GET_WIZARD_CREDENTIALS = 'GET_WIZARD_CREDENTIALS';
const UPDATE_CREDENTIAL = 'UPDATE_CREDENTIAL';
const CREATE_CREDENTIAL_SHOW = 'CREATE_CREDENTIAL_SHOW';
const EDIT_CREDENTIAL_SHOW = 'EDIT_CREDENTIAL_SHOW';
const UPDATE_CREDENTIAL_HIDE = 'UPDATE_CREDENTIAL_HIDE';
const RESET_CREDENTIAL_UPDATE_STATUS = 'RESET_CREDENTIAL_UPDATE_STATUS';

export {
  ADD_CREDENTIAL,
  UPDATE_CREDENTIAL,
  DELETE_CREDENTIAL,
  DELETE_CREDENTIALS,
  GET_CREDENTIAL,
  GET_CREDENTIALS,
  GET_WIZARD_CREDENTIALS,
  CREATE_CREDENTIAL_SHOW,
  EDIT_CREDENTIAL_SHOW,
  UPDATE_CREDENTIAL_HIDE,
  RESET_CREDENTIAL_UPDATE_STATUS
};
