const LOAD_CREDENTIALS_ERROR = 'LOAD_CREDENTIALS_ERROR';
const LOAD_CREDENTIALS_LOADING = 'LOAD_CREDENTIALS_LOADING';
const LOAD_CREDENTIALS_SUCCESS = 'LOAD_CREDENTIALS_SUCCESS';

export {
  LOAD_CREDENTIALS_ERROR,
  LOAD_CREDENTIALS_LOADING,
  LOAD_CREDENTIALS_SUCCESS
};
