const ADD_CREDENTIAL_ERROR = 'ADD_CREDENTIAL_ERROR';
const ADD_CREDENTIAL_LOADING = 'ADD_CREDENTIAL_LOADING';
const ADD_CREDENTIAL_SUCCESS = 'ADD_CREDENTIAL_SUCCESS';

const DELETE_CREDENTIAL_ERROR = 'DELETE_CREDENTIAL_ERROR';
const DELETE_CREDENTIAL_LOADING = 'DELETE_CREDENTIAL_LOADING';
const DELETE_CREDENTIAL_SUCCESS = 'DELETE_CREDENTIAL_SUCCESS';

const GET_CREDENTIAL_ERROR = 'GET_CREDENTIAL_ERROR';
const GET_CREDENTIAL_LOADING = 'GET_CREDENTIAL_LOADING';
const GET_CREDENTIAL_SUCCESS = 'GET_CREDENTIAL_SUCCESS';

const GET_CREDENTIALS_ERROR = 'GET_CREDENTIALS_ERROR';
const GET_CREDENTIALS_LOADING = 'GET_CREDENTIALS_LOADING';
const GET_CREDENTIALS_SUCCESS = 'GET_CREDENTIALS_SUCCESS';

const UPDATE_CREDENTIAL_ERROR = 'UPDATE_CREDENTIAL_ERROR';
const UPDATE_CREDENTIAL_LOADING = 'UPDATE_CREDENTIAL_LOADING';
const UPDATE_CREDENTIAL_SUCCESS = 'UPDATE_CREDENTIAL_SUCCESS';

const CREATE_CREDENTIAL_SHOW = 'CREATE_CREDENTIAL_SHOW';
const CREATE_CREDENTIAL_HIDE = 'CREATE_CREDENTIAL_HIDE';

export {
  ADD_CREDENTIAL_ERROR,
  ADD_CREDENTIAL_LOADING,
  ADD_CREDENTIAL_SUCCESS,
  DELETE_CREDENTIAL_ERROR,
  DELETE_CREDENTIAL_LOADING,
  DELETE_CREDENTIAL_SUCCESS,
  GET_CREDENTIAL_ERROR,
  GET_CREDENTIAL_LOADING,
  GET_CREDENTIAL_SUCCESS,
  GET_CREDENTIALS_ERROR,
  GET_CREDENTIALS_LOADING,
  GET_CREDENTIALS_SUCCESS,
  UPDATE_CREDENTIAL_ERROR,
  UPDATE_CREDENTIAL_LOADING,
  UPDATE_CREDENTIAL_SUCCESS,
  CREATE_CREDENTIAL_SHOW,
  CREATE_CREDENTIAL_HIDE
};
