const ADD_FACTS = 'ADD_FACTS';
const ADD_FACTS_FULFILLED = 'ADD_FACTS_FULFILLED';
const ADD_FACTS_PENDING = 'ADD_FACTS_PENDING';
const ADD_FACTS_REJECTED = 'ADD_FACTS_REJECTED';

export {
  ADD_FACTS,
  ADD_FACTS_FULFILLED,
  ADD_FACTS_PENDING,
  ADD_FACTS_REJECTED
};
