const GET_REPORTS = 'GET_REPORTS';
const GET_REPORTS_FULFILLED = 'GET_REPORTS_FULFILLED';
const GET_REPORTS_PENDING = 'GET_REPORTS_PENDING';
const GET_REPORTS_REJECTED = 'GET_REPORTS_REJECTED';

export {
  GET_REPORTS,
  GET_REPORTS_REJECTED,
  GET_REPORTS_PENDING,
  GET_REPORTS_FULFILLED
};
