const GET_REPORT_DEPLOYMENTS = 'GET_REPORT_DEPLOYMENTS';
const GET_REPORT_DEPLOYMENTS_FULFILLED = 'GET_REPORT_DEPLOYMENTS_FULFILLED';
const GET_REPORT_DEPLOYMENTS_PENDING = 'GET_REPORT_DEPLOYMENTS_PENDING';
const GET_REPORT_DEPLOYMENTS_REJECTED = 'GET_REPORT_DEPLOYMENTS_REJECTED';

const GET_REPORT_DEPLOYMENTS_CSV = 'GET_REPORT_DEPLOYMENTS_CSV';
const GET_REPORT_DEPLOYMENTS_CSV_FULFILLED = 'GET_REPORT_DEPLOYMENTS_CSV_FULFILLED';
const GET_REPORT_DEPLOYMENTS_CSV_PENDING = 'GET_REPORT_DEPLOYMENTS_CSV_PENDING';
const GET_REPORT_DEPLOYMENTS_CSV_REJECTED = 'GET_REPORT_DEPLOYMENTS_CSV_REJECTED';

const GET_REPORT_DETAILS = 'GET_REPORT_DETAILS';
const GET_REPORT_DETAILS_FULFILLED = 'GET_REPORT_DETAILS_FULFILLED';
const GET_REPORT_DETAILS_PENDING = 'GET_REPORT_DETAILS_PENDING';
const GET_REPORT_DETAILS_REJECTED = 'GET_REPORT_DETAILS_REJECTED';

const GET_REPORT_DETAILS_CSV = 'GET_REPORT_DETAILS_CSV';
const GET_REPORT_DETAILS_CSV_FULFILLED = 'GET_REPORT_DETAILS_CSV_FULFILLED';
const GET_REPORT_DETAILS_CSV_PENDING = 'GET_REPORT_DETAILS_CSV_PENDING';
const GET_REPORT_DETAILS_CSV_REJECTED = 'GET_REPORT_DETAILS_CSV_REJECTED';

export {
  GET_REPORT_DEPLOYMENTS,
  GET_REPORT_DEPLOYMENTS_FULFILLED,
  GET_REPORT_DEPLOYMENTS_PENDING,
  GET_REPORT_DEPLOYMENTS_REJECTED,
  GET_REPORT_DEPLOYMENTS_CSV,
  GET_REPORT_DEPLOYMENTS_CSV_FULFILLED,
  GET_REPORT_DEPLOYMENTS_CSV_PENDING,
  GET_REPORT_DEPLOYMENTS_CSV_REJECTED,
  GET_REPORT_DETAILS,
  GET_REPORT_DETAILS_FULFILLED,
  GET_REPORT_DETAILS_PENDING,
  GET_REPORT_DETAILS_REJECTED,
  GET_REPORT_DETAILS_CSV,
  GET_REPORT_DETAILS_CSV_FULFILLED,
  GET_REPORT_DETAILS_CSV_PENDING,
  GET_REPORT_DETAILS_CSV_REJECTED
};
