const GET_REPORT_DEPLOYMENTS = 'GET_REPORT_DEPLOYMENTS';
const GET_REPORT_DEPLOYMENTS_CSV = 'GET_REPORT_DEPLOYMENTS_CSV';
const GET_REPORT_DETAILS = 'GET_REPORT_DETAILS';
const GET_REPORT_DETAILS_CSV = 'GET_REPORT_DETAILS_CSV';

export { GET_REPORT_DEPLOYMENTS, GET_REPORT_DEPLOYMENTS_CSV, GET_REPORT_DETAILS, GET_REPORT_DETAILS_CSV };
