const ADD_SCAN_ERROR = 'ADD_SCAN_ERROR';
const ADD_SCAN_LOADING = 'ADD_SCAN_LOADING';
const ADD_SCAN_SUCCESS = 'ADD_SCAN_SUCCESS';

const DELETE_SCAN_ERROR = 'DELETE_SCAN_ERROR';
const DELETE_SCAN_LOADING = 'DELETE_SCAN_LOADING';
const DELETE_SCAN_SUCCESS = 'DELETE_SCAN_SUCCESS';

const GET_SCAN_ERROR = 'GET_SCAN_ERROR';
const GET_SCAN_LOADING = 'GET_SCAN_LOADING';
const GET_SCAN_SUCCESS = 'GET_SCAN_SUCCESS';

const GET_SCAN_CANCEL_ERROR = 'GET_SCAN_CANCEL_ERROR';
const GET_SCAN_CANCEL_LOADING = 'GET_SCAN_CANCEL_LOADING';
const GET_SCAN_CANCEL_SUCCESS = 'GET_SCAN_CANCEL_SUCCESS';

const GET_SCAN_PAUSE_ERROR = 'GET_SCAN_PAUSE_ERROR';
const GET_SCAN_PAUSE_LOADING = 'GET_SCAN_PAUSE_LOADING';
const GET_SCAN_PAUSE_SUCCESS = 'GET_SCAN_PAUSE_SUCCESS';

const GET_SCAN_RESTART_ERROR = 'GET_SCAN_RESTART_ERROR';
const GET_SCAN_RESTART_LOADING = 'GET_SCAN_RESTART_LOADING';
const GET_SCAN_RESTART_SUCCESS = 'GET_SCAN_RESTART_SUCCESS';

const GET_SCAN_RESULTS_ERROR = 'GET_SCAN_RESULTS_ERROR';
const GET_SCAN_RESULTS_LOADING = 'GET_SCAN_RESULTS_LOADING';
const GET_SCAN_RESULTS_SUCCESS = 'GET_SCAN_RESULTS_SUCCESS';

const GET_SCANS_ERROR = 'GET_SCANS_ERROR';
const GET_SCANS_LOADING = 'GET_SCANS_LOADING';
const GET_SCANS_SUCCESS = 'GET_SCANS_SUCCESS';

const UPDATE_SCAN_ERROR = 'UPDATE_SCAN_ERROR';
const UPDATE_SCAN_LOADING = 'UPDATE_SCAN_LOADING';
const UPDATE_SCAN_SUCCESS = 'UPDATE_SCAN_SUCCESS';

export {
  ADD_SCAN_ERROR,
  ADD_SCAN_LOADING,
  ADD_SCAN_SUCCESS,
  DELETE_SCAN_ERROR,
  DELETE_SCAN_LOADING,
  DELETE_SCAN_SUCCESS,
  GET_SCAN_ERROR,
  GET_SCAN_LOADING,
  GET_SCAN_SUCCESS,
  GET_SCAN_CANCEL_ERROR,
  GET_SCAN_CANCEL_LOADING,
  GET_SCAN_CANCEL_SUCCESS,
  GET_SCAN_PAUSE_ERROR,
  GET_SCAN_PAUSE_LOADING,
  GET_SCAN_PAUSE_SUCCESS,
  GET_SCAN_RESTART_ERROR,
  GET_SCAN_RESTART_LOADING,
  GET_SCAN_RESTART_SUCCESS,
  GET_SCAN_RESULTS_ERROR,
  GET_SCAN_RESULTS_LOADING,
  GET_SCAN_RESULTS_SUCCESS,
  GET_SCANS_ERROR,
  GET_SCANS_LOADING,
  GET_SCANS_SUCCESS,
  UPDATE_SCAN_ERROR,
  UPDATE_SCAN_LOADING,
  UPDATE_SCAN_SUCCESS
};
