const ADD_SCAN = 'ADD_SCAN';
const RESET_SCAN_ADD_STATUS = 'RESET_SCAN_ADD_STATUS';
const DELETE_SCAN = 'DELETE_SCAN';
const GET_SCAN = 'GET_SCAN';
const GET_SCANS = 'GET_SCANS';
const GET_SCAN_CONNECTION_RESULTS = 'GET_SCAN_CONNECTION_RESULTS';
const GET_SCAN_INSPECTION_RESULTS = 'GET_SCAN_INSPECTION_RESULTS';
const GET_SCAN_JOB = 'GET_SCAN_JOB';
const GET_SCAN_JOBS = 'GET_SCAN_JOBS';
const START_SCAN = 'START_SCAN';
const CANCEL_SCAN = 'CANCEL_SCAN';
const PAUSE_SCAN = 'PAUSE_SCAN';
const RESTART_SCAN = 'RESTART_SCAN';
const UPDATE_SCAN = 'UPDATE_SCAN';
const GET_MERGE_SCAN_RESULTS = 'GET_MERGE_SCAN_RESULTS';
const MERGE_SCAN_DIALOG_SHOW = 'MERGE_SCAN_DIALOG_SHOW';
const MERGE_SCAN_DIALOG_HIDE = 'MERGE_SCAN_DIALOG_HIDE';

export {
  ADD_SCAN,
  RESET_SCAN_ADD_STATUS,
  DELETE_SCAN,
  GET_SCAN,
  GET_SCANS,
  GET_SCAN_CONNECTION_RESULTS,
  GET_SCAN_INSPECTION_RESULTS,
  GET_SCAN_JOB,
  GET_SCAN_JOBS,
  START_SCAN,
  CANCEL_SCAN,
  PAUSE_SCAN,
  RESTART_SCAN,
  UPDATE_SCAN,
  GET_MERGE_SCAN_RESULTS,
  MERGE_SCAN_DIALOG_SHOW,
  MERGE_SCAN_DIALOG_HIDE
};
