const LOAD_SCANS_ERROR = 'LOAD_SCANS_ERROR';
const LOAD_SCANS_LOADING = 'LOAD_SCANS_LOADING';
const LOAD_SCANS_SUCCESS = 'LOAD_SCANS_SUCCESS';

export { LOAD_SCANS_ERROR, LOAD_SCANS_LOADING, LOAD_SCANS_SUCCESS };
