const ADD_SOURCE = 'ADD_SOURCE';
const ADD_SOURCE_FULFILLED = 'ADD_SOURCE_FULFILLED';
const ADD_SOURCE_PENDING = 'ADD_SOURCE_PENDING';
const ADD_SOURCE_REJECTED = 'ADD_SOURCE_REJECTED';

const DELETE_SOURCE = 'DELETE_SOURCE';
const DELETE_SOURCE_FULFILLED = 'DELETE_SOURCE_FULFILLED';
const DELETE_SOURCE_PENDING = 'DELETE_SOURCE_PENDING';
const DELETE_SOURCE_REJECTED = 'DELETE_SOURCE_REJECTED';

const GET_SOURCE = 'GET_SOURCE';
const GET_SOURCE_FULFILLED = 'GET_SOURCE_FULFILLED';
const GET_SOURCE_PENDING = 'GET_SOURCE_PENDING';
const GET_SOURCE_REJECTED = 'GET_SOURCE_REJECTED';

const GET_SOURCES = 'GET_SOURCES';
const GET_SOURCES_FULFILLED = 'GET_SOURCES_FULFILLED';
const GET_SOURCES_PENDING = 'GET_SOURCES_PENDING';
const GET_SOURCES_REJECTED = 'GET_SOURCES_REJECTED';

const UPDATE_SOURCE = 'UPDATE_SOURCE';
const UPDATE_SOURCE_FULFILLED = 'UPDATE_SOURCE_FULFILLED';
const UPDATE_SOURCE_PENDING = 'UPDATE_SOURCE_PENDING';
const UPDATE_SOURCE_REJECTED = 'UPDATE_SOURCE_REJECTED';

const SOURCES_SELECTED = 'SOURCES_SELECTED';

export {
  ADD_SOURCE,
  ADD_SOURCE_FULFILLED,
  ADD_SOURCE_PENDING,
  ADD_SOURCE_REJECTED,
  DELETE_SOURCE,
  DELETE_SOURCE_FULFILLED,
  DELETE_SOURCE_PENDING,
  DELETE_SOURCE_REJECTED,
  GET_SOURCE,
  GET_SOURCE_FULFILLED,
  GET_SOURCE_PENDING,
  GET_SOURCE_REJECTED,
  GET_SOURCES,
  GET_SOURCES_FULFILLED,
  GET_SOURCES_PENDING,
  GET_SOURCES_REJECTED,
  UPDATE_SOURCE,
  UPDATE_SOURCE_FULFILLED,
  UPDATE_SOURCE_PENDING,
  UPDATE_SOURCE_REJECTED,
  SOURCES_SELECTED
};
