const SET_FILTER_TYPE = 'SET_FILTER_TYPE';
const SET_FILTER_VALUE = 'SET_FILTER_VALUE';
const ADD_FILTER = 'ADD_FILTER';
const REMOVE_FILTER = 'REMOVE_FILTER';
const CLEAR_FILTERS = 'CLEAR_FILTERS';
const SET_SORT_TYPE = 'SET_SORT_TYPE';
const TOGGLE_SORT_ASCENDING = 'TOGGLE_SORT_ASCENDING';

export {
  SET_FILTER_TYPE,
  SET_FILTER_VALUE,
  ADD_FILTER,
  REMOVE_FILTER,
  CLEAR_FILTERS,
  SET_SORT_TYPE,
  TOGGLE_SORT_ASCENDING
};
