const LOAD_SOURCES_ERROR = 'LOAD_SOURCES_ERROR';
const LOAD_SOURCES_LOADING = 'LOAD_SOURCES_LOADING';
const LOAD_SOURCES_SUCCESS = 'LOAD_SOURCES_SUCCESS';

export { LOAD_SOURCES_ERROR, LOAD_SOURCES_LOADING, LOAD_SOURCES_SUCCESS };
