const ADD_SOURCE = 'ADD_SOURCE';
const DELETE_SOURCE = 'DELETE_SOURCE';
const DELETE_SOURCES = 'DELETES_SOURCE';
const GET_SCANS_SOURCES = 'GET_SCANS_SOURCES';
const GET_SOURCE = 'GET_SOURCE';
const GET_SOURCES = 'GET_SOURCES';
const UPDATE_SOURCES = 'UPDATE_SOURCES';
const UPDATE_SOURCE = 'UPDATE_SOURCE';
const UPDATE_SOURCE_WIZARD = 'UPDATE_SOURCE_WIZARD';
const VALID_SOURCE_WIZARD_STEPONE = 'VALID_SOURCE_WIZARD_STEPONE';
const VALID_SOURCE_WIZARD_STEPTWO = 'VALID_SOURCE_WIZARD_STEPTWO';
const CREATE_SOURCE_SHOW = 'CREATE_SOURCE_SHOW';
const EDIT_SOURCE_SHOW = 'EDIT_SOURCE_SHOW';
const UPDATE_SOURCE_HIDE = 'UPDATE_SOURCE_HIDE';

export {
  ADD_SOURCE,
  DELETE_SOURCE,
  DELETE_SOURCES,
  GET_SCANS_SOURCES,
  GET_SOURCE,
  GET_SOURCES,
  UPDATE_SOURCES,
  UPDATE_SOURCE,
  UPDATE_SOURCE_WIZARD,
  VALID_SOURCE_WIZARD_STEPONE,
  VALID_SOURCE_WIZARD_STEPTWO,
  CREATE_SOURCE_SHOW,
  EDIT_SOURCE_SHOW,
  UPDATE_SOURCE_HIDE
};
