const STATUS_INFO = 'STATUS_INFO';
const STATUS_INFO_FULFILLED = 'STATUS_INFO_FULFILLED';
const STATUS_INFO_PENDING = 'STATUS_INFO_PENDING';
const STATUS_INFO_REJECTED = 'STATUS_INFO_REJECTED';

export { STATUS_INFO, STATUS_INFO_FULFILLED, STATUS_INFO_PENDING, STATUS_INFO_REJECTED };
