const TOAST_ADD = 'TOAST_ADD';
const TOAST_REMOVE = 'TOAST_REMOVE';
const TOAST_PAUSE = 'TOAST_PAUSE';
const TOAST_RESUME = 'TOAST_RESUME';

export { TOAST_ADD, TOAST_REMOVE, TOAST_PAUSE, TOAST_RESUME };
