const USER_AUTH = 'USER_AUTH';
const USER_AUTH_FULFILLED = 'USER_AUTH_FULFILLED';
const USER_AUTH_PENDING = 'USER_AUTH_PENDING';
const USER_AUTH_REJECTED = 'USER_AUTH_REJECTED';

const USER_INFO = 'USER_INFO';
const USER_INFO_FULFILLED = 'USER_INFO_FULFILLED';
const USER_INFO_PENDING = 'USER_INFO_PENDING';
const USER_INFO_REJECTED = 'USER_INFO_REJECTED';

const USER_LOGOUT = 'USER_LOGOUT';
const USER_LOGOUT_FULFILLED = 'USER_LOGOUT_FULFILLED';
const USER_LOGOUT_PENDING = 'USER_LOGOUT_PENDING';
const USER_LOGOUT_REJECTED = 'USER_LOGOUT_REJECTED';

export {
  USER_AUTH,
  USER_AUTH_FULFILLED,
  USER_AUTH_PENDING,
  USER_AUTH_REJECTED,
  USER_INFO,
  USER_INFO_FULFILLED,
  USER_INFO_PENDING,
  USER_INFO_REJECTED,
  USER_LOGOUT,
  USER_LOGOUT_FULFILLED,
  USER_LOGOUT_PENDING,
  USER_LOGOUT_REJECTED
};
