const VIEW_FIRST_PAGE = 'VIEW_FIRST_PAGE';
const VIEW_LAST_PAGE = 'VIEW_LAST_PAGE';
const VIEW_PREVIOUS_PAGE = 'VIEW_PREVIOUS_PAGE';
const VIEW_NEXT_PAGE = 'VIEW_NEXT_PAGE';
const VIEW_PAGE_NUMBER = 'VIEW_PAGE_NUMBER';
const SET_PER_PAGE = 'SET_PER_PAGE';

export { VIEW_FIRST_PAGE, VIEW_LAST_PAGE, VIEW_PREVIOUS_PAGE, VIEW_NEXT_PAGE, VIEW_PAGE_NUMBER, SET_PER_PAGE };
