const SOURCES_VIEW = 'SOURCES_VIEW';
const SCANS_VIEW = 'SCANS_VIEW';
const CREDENTIALS_VIEW = 'CREDENTIALS_VIEW';

const SELECT_ITEM = 'SELECT_ITEM';
const DESELECT_ITEM = 'DESELECT_ITEM';
const EXPAND_ITEM = 'EXPAND_ITEM';

export { SOURCES_VIEW, SCANS_VIEW, CREDENTIALS_VIEW, SELECT_ITEM, DESELECT_ITEM, EXPAND_ITEM };
