---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "jboss_fuse_on_karaf"

# Tasks that can locate a KARAF_HOME directory
- name: Gather jboss.fuse-on-karaf.running-paths
  # This command deserves some explanation.

  # ps -A -o args: list all of the processes. It's important
  # for the next step that the executable name is the first
  # thing on the command line, which '-o args' does.

  # egrep ... : we are about to look for processes with
  # 'karaf.base' and 'karaf.home' in their command
  # line. Unfortunately, our sed process and the shell that is
  # running our pipeline both qualify. The ^sed excludes sed, and
  # the '\| sed' excludes the shell.

  # sed ...: get the value of command-line arguments of the form
  # '-Dkaraf.base=...' and '-Dkaraf.home=...'. The Karaf
  # documentation says that karaf.base defaults to karaf.home, but
  # there's no documentation of what goes where if they're
  # different, so we check both.

  # xargs -n 1 readlink: normalize home directory paths so the
  # 'unique' below really does deduplicate them.

  raw: ps -A -o args | egrep --invert-match '(^sed)|(\| sed)' | sed -n -e 's/.*-Dkaraf.base=\([^[:space:]]*\).*/\1/pg;s/.*-Dkaraf.home=\([^[:space:]]*\).*/\1/pg' | xargs -n 1 --no-run-if-empty readlink --canonicalize
  register: karaf_running_processes
  ignore_errors: yes
  when: 'jboss_fuse'

- name: Use locate to look for karaf.jar

  # We look for karaf.jar. We expect that it will be located at
  # $KARAF_HOME/lib/karaf.jar, so strip off the lib/karaf.jar part
  # to get the KARAF_HOME. Just like the last task, we also use
  # realpath to normalize paths.

  raw: locate karaf.jar | sed -n -e 's/\(.*\)lib\/karaf\.jar$/\1/p' | xargs -n 1 --no-run-if-empty readlink --canonicalize
  register: karaf_locate_karaf_jar
  ignore_errors: yes
  when: 'internal_have_locate and jboss_fuse'

- name: Use find to look for karaf.jar
  raw: find {{search_directories}} -xdev -type f -name karaf.jar 2> /dev/null | sed -n -e 's/\(.*\)lib\/karaf\.jar$/\1/p' | xargs -n 1 --no-run-if-empty readlink --canonicalize | sort -u
  register: karaf_find_karaf_jar
  ignore_errors: yes
  when: 'jboss_fuse_ext'

# Combine the outputs of the above into a single fact

- name: combine KARAF_HOME candidates into single list
  set_fact:
      karaf_homes: "{{
          (karaf_running_processes.get('stdout_lines', []) +
            karaf_locate_karaf_jar.get('stdout_lines', []) +
            karaf_find_karaf_jar.get('stdout_lines', [])) | unique }}"
  ignore_errors: yes
  when: 'jboss_fuse'

# Look for fuse inside KARAF_HOME directories

- name: check bin/fuse
  raw: ls -1 "{{ item }}"/bin/fuse 2>/dev/null
  register: karaf_home_bin_fuse
  ignore_errors: yes
  with_items: "{{ karaf_homes }}"
  when: 'jboss_fuse'


- name: check system/org/jboss/fuse
  raw: ls -1 "{{ item }}"/system/org/jboss 2>/dev/null
  register: karaf_home_system_org_jboss
  ignore_errors: yes
  with_items: "{{ karaf_homes }}"
  when: 'jboss_fuse'


# Tests that can indicate the presence of Fuse, but can't tell us the
# KARAF_HOME (or even whether it's Fuse-on-Karaf or Fuse-on-EAP).

- name: look for fuse systemd service
  raw: systemctl list-unit-files --no-pager
  register: jboss_fuse_systemctl_unit_files
  ignore_errors: yes
  become: true
  when: 'jboss_fuse'

- name: look for fuse in chkconfig
  raw: chkconfig --list
  register: jboss_fuse_chkconfig
  ignore_errors: yes
  become: true
  when: 'jboss_fuse'

- name: Use locate to look for camel-ver
  raw: locate camel-core | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p'
  register: jboss_fuse_camel_ver
  ignore_errors: yes
  when: 'internal_have_locate and jboss_fuse'

- name: check /system/org/apache/camel/camel-core for camel-ver
  raw: ls -1 '{{ item }}/system/org/apache/camel/camel-core' 2>/dev/null | sed -n 's/^.*\(redhat-[0-9]\{6\}\).*/\1/p'
  register: jboss_fuse_on_karaf_camel_ver
  ignore_errors: yes
  with_items: "{{ karaf_homes }}"
  when: 'jboss_fuse'

- name: set the camel-ver fact
  set_fact:
      fuse_camel_version: "{{
      (jboss_fuse_camel_ver.get('stdout_lines', []) +
       jboss_fuse_on_karaf_camel_ver.get('stdout_lines', [])) | unique }}"
  ignore_errors: yes
  when: 'jboss_fuse'

- name: Use locate to look for activemq-ver
  raw: locate activemq | sed -n 's/^.*\(redhat-[0-9]\{6\}\).*/\1/p'
  register: jboss_fuse_activemq_ver
  ignore_errors: yes
  when: 'internal_have_locate and jboss_fuse'

- name: check /system/org/apache/activemq/activemq-camel for activemq-ver
  raw: ls -1 '{{ item }}/system/org/apache/activemq/activemq-camel' 2>/dev/null | sed -n 's/^.*\(redhat-[0-9]\{6\}\).*/\1/p'
  register: jboss_fuse_on_karaf_activemq_ver
  ignore_errors: yes
  with_items: "{{ karaf_homes }}"
  when: 'jboss_fuse'

- name: set the activemq-version fact
  set_fact:
      fuse_activemq_version: "{{
      (jboss_fuse_activemq_ver.get('stdout_lines', []) +
       jboss_fuse_on_karaf_activemq_ver.get('stdout_lines', [])) | unique }}"
  ignore_errors: yes
  when: 'jboss_fuse'

- name: Use locate to look for cxf-rt-ver
  raw: locate cxf-rt| sed -n 's/^.*\(redhat-[0-9]\{6\}\).*/\1/p'
  register: jboss_fuse_cxf_ver
  ignore_errors: yes
  when: 'internal_have_locate and jboss_fuse'

- name: check /system/org/apache/cxf/cxf-rt-bindings-coloc for cxf-rt
  raw: ls -1 '{{ item }}/system/org/apache/cxf/cxf-rt-bindings-coloc' 2>/dev/null | sed -n 's/^.*\(redhat-[0-9]\{6\}\).*/\1/p'
  register: jboss_fuse_on_karaf_cxf_ver
  ignore_errors: yes
  with_items: "{{ karaf_homes }}"
  when: 'jboss_fuse'

- name: set the cxf-rt fact
  set_fact:
      fuse_cxf_version: "{{
      (jboss_fuse_cxf_ver.get('stdout_lines', []) +
       jboss_fuse_on_karaf_cxf_ver.get('stdout_lines', [])) | unique }}"
  ignore_errors: yes
  when: 'jboss_fuse'