---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "installed_products"

- name: gather internal_installed_products
  raw: export LANG=C LC_ALL=C; find /etc/pki/product*/ -name '*pem' -exec rct cat-cert --no-content '{}' \; | grep -B2 -A4 -E '^\s+ID:'
  register: internal_installed_products
  ignore_errors: yes
  when: 'internal_have_rct_user'

- name: set installed_products fact
  set_fact:
    installed_products: "{{ internal_installed_products }}"
  ignore_errors: yes
  when: 'internal_installed_products.get("rc") == 0'

- name: initialize rhel_version fact
  set_fact:
    rhel_version: "QUIPUCORDS_FORCE_POST_PROCESS"
  ignore_errors: yes
