---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "system_purpose"

- name: gather internal_system_purpose_json
  raw: export LANG=C LC_ALL=C; if [ -f /etc/rhsm/syspurpose/syspurpose.json ] ; then cat /etc/rhsm/syspurpose/syspurpose.json 2>/dev/null; fi
  register: internal_system_purpose_json
  ignore_errors: yes

- name: set system_purpose_json fact
  set_fact:
    system_purpose_json: "{{internal_system_purpose_json}}"
  ignore_errors: yes
