---

- name: gather etc-issue.etc-issue fact
  raw: if [ -f /etc/issue ] ; then cat /etc/issue ; fi
  register: internal_etc_issue_cmd
  ignore_errors: yes

- name: set etc_issue
  set_fact:
    etc_issue: "{{ internal_etc_issue_cmd['stdout'] | default('') }}"

- name: gather instnum.instnum fact
  raw: if [ -f /etc/sysconfig/rhn/install-num ] ; then cat /etc/sysconfig/rhn/install-num ; fi
  register: internal_instnum_cmd
  ignore_errors: yes

- name: set instnum
  set_fact:
    instnum: "{{ internal_instnum_cmd['stdout'] | default('') }}"

- name: gather systemid fact
  raw: if [ -f /etc/sysconfig/rhn/systemid ] ; then cat /etc/sysconfig/rhn/systemid ; fi
  register: internal_systemid_cmd
  ignore_errors: yes

- name: set systemid
  set_fact:
    systemid: "{{ internal_systemid_cmd['stdout'] | default('') }}"
