---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "uname"

- name: gather internal_uname_hostname fact
  raw: export LANG=C LC_ALL=C; uname -n
  register: internal_uname_hostname
  ignore_errors: yes

- name: add uname.hostname to dictionary
  set_fact:
    uname_hostname: "{{ internal_uname_hostname | json_query('stdout_lines[-1]') | default('') }}"
  ignore_errors: yes

- name: gather internal_uname_processor fact
  raw: export LANG=C LC_ALL=C; uname -p
  register: internal_uname_processor
  ignore_errors: yes

- name: add uname_processor to dictionary
  set_fact:
    uname_processor: "{{ internal_uname_processor | json_query('stdout_lines[-1]') | default('') }}"
  ignore_errors: yes

- name: gather internal_uname_all fact
  raw: export LANG=C LC_ALL=C; uname -a
  register: internal_uname_all
  ignore_errors: yes

- name: add uname.all to dictionary
  set_fact:
    uname_all: "{{ internal_uname_all | json_query('stdout_lines[-1]') | default('') }}"
  ignore_errors: yes
