---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "virt"

- name: check if privcmd exists
  raw: if [ -e /proc/xen/privcmd ]; then echo "Y"; else echo "N"; fi
  register: virt_xen_privcmd_found
  ignore_errors: yes

- name: check if kvm exists
  raw: if [ -e /dev/kvm ]; then echo "Y"; else echo "N"; fi
  register: virt_kvm_found
  ignore_errors: yes

- name: check for xen guests
  raw: ps aux | grep xend | grep -v grep | wc -l
  register: virt_xen_guest
  ignore_errors: yes

- name: set system manufacture
  raw: manufacturer=$(/usr/sbin/dmidecode | grep -A4 'System Information' | grep 'Manufacturer' | sed -n -e 's/^.*Manufacturer:\s//p')
  register: virt_sys_manufacturer_cmd
  become: yes
  ignore_errors: yes
  when: 'have_dmidecode'

- name: extract result value for virt_sys_manufacturer_cmd
  set_fact:
    virt_sys_manufacturer: "{{  virt_sys_manufacturer_cmd['stdout_lines'][0] | trim | default('') }}"
  ignore_errors: yes
  when: '"stdout_lines" in virt_sys_manufacturer_cmd'

- name: handle failure value for virt_sys_manufacturer
  set_fact:
    virt_sys_manufacturer: ""
  ignore_errors: yes
  when: '"stdout_lines" not in virt_sys_manufacturer_cmd'

- name: check cpu model name for QEMU
  raw: model_name=$(cat /proc/cpuinfo 2>/dev/null | grep '^model name\s*:' | sed -n -e 's/^.*model name\s*:\s//p'); if [[ $model_name == *QEMU ]]; then echo "Y"; else echo "N"; fi
  register: virt_cpu_model_name_kvm
  ignore_errors: yes

- name: initialize virt.type
  set_fact: virt_type=""
  ignore_errors: yes

- name: initialize virt.virt
  set_fact: virt_virt=""
  ignore_errors: yes

- name: gather virt.num_guests fact
  raw: virsh -c qemu:///system --readonly list --all | wc -l
  register: virt_num_guests
  ignore_errors: yes
  when: 'internal_have_virsh'

- name: extract output virt.num_guests fact
  set_fact: virt_num_guests="{{ (virt_num_guests | json_query('stdout_lines[0]')) if internal_have_virsh else None }}"
  ignore_errors: yes

- name: gather virt.num_running_guests fact
  raw: virsh -c qemu:///system --readonly list --uuid | wc -l
  register: internal_virt_num_running_guests
  ignore_errors: yes
  when: 'internal_have_virsh'

- name: extract output virt.num_running_guests fact
  set_fact: virt_num_running_guests="{{ (internal_virt_num_running_guests | json_query('stdout_lines[0]')) if internal_have_virsh else None }}"
  ignore_errors: yes
