---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "jboss_fuse"


# This will scan linux systems for JBoss Fuse, ActiveMQ, CXF, Camel or Community  Installations
- name: Gather jboss.activemq-ver
  raw: FOUND=""; for jar in `find {{search_directories}} -type f -xdev -name \*activemq-\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
  register: jboss_activemq_ver
  ignore_errors: yes
  when: 'jboss_fuse_ext'

- name: Gather jboss.camel-ver
  raw: FOUND=""; for jar in `find {{search_directories}} -type f -xdev -name \*camel-core\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
  register: jboss_camel_ver
  ignore_errors: yes
  when: 'jboss_fuse_ext'

- name: Gather jboss.cxf-ver
  raw: FOUND=""; for jar in `find {{search_directories}} -type f -xdev -name \*cxf-rt\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
  register: jboss_cxf_ver
  ignore_errors: yes
  when: 'jboss_fuse_ext'
