---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "virt_what"

- name: execute virt-what
  raw: export LANG=C LC_ALL=C; virt-what
  register: internal_virt_what_output
  ignore_errors: yes
  become: yes
  when: 'user_has_sudo and internal_have_virt_what'

- name: set virt-what fact
  set_fact:
    virt_what: "{{ internal_virt_what_output }}"
