---

- name: internal_host_started_processing_role
  set_fact:
    internal_host_started_processing_role: "insights"

- name: gather insights.machine-id
  raw: if [ -f /etc/insights-client/machine-id ] ; then cat /etc/insights-client/machine-id; fi || if [ -f /etc/redhat-access-insights ] ; then cat /etc/redhat-access-insights/machine-id; fi
  register: internal_get_insights_client_id
  ignore_errors: yes

- name: extract insights client id from internal_get_insights_client_id
  set_fact:
    insights_client_id: "{{ internal_get_insights_client_id.get('stdout') | default('') }}"
  ignore_errors: yes
