---
- hosts: " {{ variable_host | default('all') }} "
  gather_facts: no
  # update roles structure when we transition off ansible 2.3
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
  roles:
    # IMPORTANT NOTE:
    # The order of these roles is specific and deliberate.
    # Do not sort or reorder these without specific reasons.
    - user_data
    - check_dependencies
    - connection
    - virt
    - cpu
    - date
    - dmi
    - cloud_provider
    - etc_release
    - file_contents
    - ifconfig
    - ip
    - installed_products
    - redhat_packages
    - subman
    - uname
    - virt_what
    - insights
    - system_purpose
    - redhat_release
    - memory
    - jboss_eap
    - jboss_eap5
    - jboss_brms
    - jboss_fuse
    - jboss_ws
    - jboss_fuse_on_karaf
    - host_done
