---

# subman_cpu_cpu fact
- name: gather subman.cpu.cpu(s) fact
  raw: subscription-manager facts --list | grep '^cpu.cpu(s).' | sed -n -e 's/^.*cpu.cpu(s).\s*//p'
  register: internal_subman_cpu_cpu_cmd
  ignore_errors: yes
  become: yes
  when: 'internal_have_subscription_manager'

- name: extract result value for subman.cpu.cpu(s)
  set_fact:
    subman_cpu_cpu: "{{ internal_subman_cpu_cpu_cmd['stdout'] | trim | default(None) }}"
  when: '"stdout" in internal_subman_cpu_cpu_cmd'

# subman_cpu_core_per_socket fact
- name: gather subman.cpu.core(s)_per_socket fact
  raw: subscription-manager facts --list | grep '^cpu.core(s)_per_socket.' | sed -n -e 's/^.*cpu.core(s)_per_socket.\s*//p'
  register: internal_subman_cpu_core_per_socket_cmd
  ignore_errors: yes
  become: yes
  when: 'internal_have_subscription_manager'

- name: extract result value for subman.cpu.core(s)_per_socket
  set_fact:
    subman_cpu_core_per_socket: "{{  internal_subman_cpu_core_per_socket_cmd['stdout'] | trim | default(None) }}"
  when: '"stdout" in internal_subman_cpu_core_per_socket_cmd'

# subman_cpu_cpu_socket fact
- name: gather subman.cpu.cpu_socket(s) fact
  raw: subscription-manager facts --list | grep '^cpu.cpu_socket(s).' | sed -n -e 's/^.*cpu.cpu_socket(s).\s*//p'
  register: internal_subman_cpu_cpu_socket_cmd
  ignore_errors: yes
  become: yes
  when: 'internal_have_subscription_manager'

- name: extract result value for subman.cpu.cpu_socket(s)
  set_fact:
    subman_cpu_cpu_socket: "{{  internal_subman_cpu_cpu_socket_cmd['stdout'] | trim | default(None) }}"
  when: '"stdout" in internal_subman_cpu_cpu_socket_cmd'

# subman_virt_host_type fact
- name: gather subman.virt.host_type fact
  raw: subscription-manager facts --list | grep '^virt.host_type.' | sed -n -e 's/^.*virt.host_type.\s*//p'
  register: internal_subman_virt_host_type_cmd
  ignore_errors: yes
  become: yes
  when: 'internal_have_subscription_manager'

- name: extract result value for subman.virt.host_type
  set_fact:
    subman_virt_host_type: "{{  internal_subman_virt_host_type_cmd['stdout'] | trim | default(None) }}"
  when: '"stdout" in internal_subman_virt_host_type_cmd'

# subman_virt_is_guest fact
- name: gather subman.virt.is_guest fact
  raw: subscription-manager facts --list | grep '^virt.is_guest.' | sed -n -e 's/^.*virt.is_guest.\s*//p'
  register: internal_subman_virt_is_guest_cmd
  ignore_errors: yes
  become: yes
  when: 'internal_have_subscription_manager'

- name: extract result value for subman.virt.is_guest
  set_fact:
    subman_virt_is_guest: "{{  internal_subman_virt_is_guest_cmd['stdout'] | string() | trim | default(None) }}"
  when: '"stdout" in internal_subman_virt_is_guest_cmd'

# subman_virt_uuid fact
- name: gather subman.virt.uuid fact
  raw: subscription-manager facts --list | grep '^virt.uuid.' | sed -n -e 's/^.*virt.uuid.\s*//p'
  register: internal_subman_virt_uuid_cmd
  ignore_errors: yes
  become: yes
  when: 'internal_have_subscription_manager'

- name: extract result value for subman.virt.uuid
  set_fact:
    subman_virt_uuid: "{{  internal_subman_virt_uuid_cmd['stdout'] | trim | default(None) }}"
  when: '"stdout" in internal_subman_virt_uuid_cmd'

# subman fact
- name: gather subman.has_facts_file fact
  raw: fact_count=$(ls /etc/rhsm/facts | grep .facts | wc -l); if [[ $fact_count > 0 ]]; then echo "Y"; else echo "N"; fi
  register: internal_subman_has_facts_file
  ignore_errors: yes
  when: 'internal_have_subscription_manager'

- name: add subman.has_facts_file to dictionary
  set_fact:
    subman: "{{ subman|default({}) | combine({ item: internal_subman_has_facts_file['stdout'] | trim | default(None) }) }}"
  with_items:
  - 'subman.has_facts_file'
  when: 'internal_have_subscription_manager'

# subman_consumed fact
- name: gather subman.consumed fact
  raw: subscription-manager list --consumed | grep -e '^SKU' -e '^Subscription Name' | sed -n -e 's/SKU\s*.\s*//p' -e 's/Subscription Name\s*.\s*//p' | awk '{ ORS = (NR%2 ? " - " {{":"}} RS) } 1'
  register: internal_subman_consumed_cmd
  ignore_errors: yes
  become: yes
  when: 'internal_have_subscription_manager'

- name: extract result value for subman.consumed
  set_fact:
    subman_consumed: "{{  internal_subman_consumed_cmd['stdout'] | trim | default(None) }}"
  when: '"stdout" in internal_subman_consumed_cmd'
